### ISSUE TITLE
Shelly Plus 1PM devices

### ISSUE THREAD

**Issue by Elix-g** [esphome/esphome-devices#497]
Some information on the device pages of [Shelly Plus 1 PM](https://devices.esphome.io/devices/Shelly-Plus-1PM) and [Shelly Plis i4](https://devices.esphome.io/devices/Shelly-Plus-i4) are wrong or incomplete. Those device is based on ESP32-U4WDH Rev 3.0 which is NOT a single core SOC operating at 160MHz. In fact, there are just slight differences to ESP32-WROOM, please have a look to the [espressif website](https://products.espressif.com/#/product-comparison).

Three of my devices are identified by esptool.py as ESP32-U4WDH (revision 3.0), features: Dual Core at 240MHz.

![image](https://github.com/esphome/esphome-devices/assets/37552418/3968df0a-6f84-460d-8c9a-dbdc5d691b53)

Compiling and running ESPHome for them is totally fine using ESP32 defaults:

```

...

esphome:
  name: ${device_name}
  comment: ${device_description}
  project:
    name: "${project_name}"
    version: "${project_version}"

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y

...

```

For [Shelly Plus 2PM](https://devices.esphome.io/devices/Shelly-Plus-2PM), there are information about different PCB revisions. Those should be added to 1PM and i4 as well. In case you need pictures, I'll open one of my devices and take some pics.
